version: "3.7"

services:
  app:
    container_name: "app-data-mapper"
    build:
      context: .
      args:
        - user=${APP_USER}
        - uid=${APP_UID}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_PATH}:/var/www
    networks:
      - data-mapper

  nginx:
    container_name: "nginx-data-mapper"
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APP_PATH}:/var/www
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
    networks:
      - data-mapper

  mysql:
    container_name: "mysql-data-mapper"
    build:
      context: docker/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_WORKSPACE_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - data-mapper

networks:
  data-mapper:
    driver: bridge
